### PR TITLE
Various improvements to project structure and implementation

### PR DESCRIPTION
**Pull request by ebfull**
This makes wNAF/multiexp more modularized and abstract (for use later in remodeling groth) and starts moving other things around.

Also, good chance to start working on buildbot.

### CODE REVIEW

**Comment by ebfull** [comment]
@bmerge r+

**Comment by bmerge** [comment]
:pushpin: Commit e9dee9d has been approved by `ebfull`

**Comment by bmerge** [comment]
:hourglass: Testing commit e9dee9de16623ff676feae06f6112afd9ab091dd with merge 9daac82f94d47cf2256c6c51d6b619edd677f4a6...

**Comment by bmerge** [comment]
:broken_heart: Test failed - [windows64msvc-auto](http://ci.bellman.rs:8010//builders/windows64msvc-auto/builds/0)

**Comment by ebfull** [comment]
@bmerge retry

**Comment by bmerge** [comment]
:hourglass: Testing commit e9dee9de16623ff676feae06f6112afd9ab091dd with merge fb07c08a269a314fd5216493b7314b47dd4d9f39...

**Comment by ebfull** [comment]
@bmerge r+

**Comment by bmerge** [comment]
:hourglass: Testing commit e9dee9de16623ff676feae06f6112afd9ab091dd with merge 252f374b6768899c219a515241327bf8cca9695a...

**Comment by bmerge** [comment]
:hourglass: Testing commit e9dee9de16623ff676feae06f6112afd9ab091dd with merge 9ea9a245ede93f3862fed764539badef74c63b4a...

**Comment by ebfull** [comment]
@bmerge retry

**Comment by bmerge** [comment]
:hourglass: Testing commit e9dee9de16623ff676feae06f6112afd9ab091dd with merge 732af319fe9753ba1923654e34ecfb2c8b79eac6...

**Comment by bmerge** [comment]
:sunny: Test successful - [windows64msvc-auto](http://ci.bellman.rs:8010//builders/windows64msvc-auto/builds/4)
Approved by: ebfull
Pushing 732af319fe9753ba1923654e34ecfb2c8b79eac6 to master...

**Pull request merged**
