### PR TITLE
Fix comment about sqrt.

### PR DESCRIPTION
**Pull request by ebfull**
Still just testing CI stuff.

### CODE REVIEW

**Comment by ebfull** [comment]
@bmerge r+

**Comment by bmerge** [comment]
:pushpin: Commit 9c94216 has been approved by `ebfull`

**Comment by bmerge** [comment]
:hourglass: Testing commit 9c94216a87159817735ff8fb08af23af817fa102 with merge 99bcabca44db21936fee208546839f04a1b92eca...

**Comment by bmerge** [comment]
:broken_heart: Test failed - [windows64msvc-auto](http://ci.bellman.rs:8010/builders/windows64msvc-auto/builds/9)

**Comment by ebfull** [comment]
@bmerge retry

**Comment by bmerge** [comment]
:hourglass: Testing commit 9c94216a87159817735ff8fb08af23af817fa102 with merge e282bc095ad10345e0e8e5bba42feac6501b44d4...

**Comment by bmerge** [comment]
:broken_heart: Test failed - [linux32-auto](http://ci.bellman.rs:8010/builders/linux32-auto/builds/1)

**Comment by ebfull** [comment]
@bmerge retry

**Comment by bmerge** [comment]
:zap: Previous build results for [linux64-auto](http://ci.bellman.rs:8010/builders/linux64-auto/builds/6), [windows32msvc-auto](http://ci.bellman.rs:8010/builders/windows32msvc-auto/builds/1) are reusable. Rebuilding only [linux32-auto](http://ci.bellman.rs:8010/builders/linux32-auto/builds/1), [windows64msvc-auto](http://ci.bellman.rs:8010/builders/windows64msvc-auto/builds/10)...

**Comment by bmerge** [comment]
:sunny: Test successful - [linux32-auto](http://ci.bellman.rs:8010/builders/linux32-auto/builds/3), [linux64-auto](http://ci.bellman.rs:8010/builders/linux64-auto/builds/6), [windows32msvc-auto](http://ci.bellman.rs:8010/builders/windows32msvc-auto/builds/1), [windows64msvc-auto](http://ci.bellman.rs:8010/builders/windows64msvc-auto/builds/11)
Approved by: ebfull
Pushing e282bc095ad10345e0e8e5bba42feac6501b44d4 to master...

**Pull request merged**
