### PR TITLE
Version bump

### PR DESCRIPTION
**Pull request by ebfull**

### CODE REVIEW

**Comment by ebfull** [comment]
@bmerge r+

**Comment by bmerge** [comment]
:pushpin: Commit 5ca9341 has been approved by `ebfull`

**Comment by bmerge** [comment]
:hourglass: Testing commit 5ca9341aeb1956c6e54e0c02b074fe7ab61d9e5c with merge be1961124c762beb12c257a946513b193432f9ac...

**Comment by bmerge** [comment]
:sunny: Test successful - [linux64-auto](http://ci.bellman.rs:8010/builders/linux64-auto/builds/4), [windows64msvc-auto](http://ci.bellman.rs:8010/builders/windows64msvc-auto/builds/8)
Approved by: ebfull
Pushing be1961124c762beb12c257a946513b193432f9ac to master...

**Pull request merged**
