### PR TITLE
Version bump

### PR DESCRIPTION
**Pull request by ebfull**

### CODE REVIEW

**Comment by ebfull** [comment]
@bmerge try

**Comment by bmerge** [comment]
:hourglass: Trying commit 5ca9341aeb1956c6e54e0c02b074fe7ab61d9e5c with merge d842d514418d29087008f6bbee6f9a64f5b9cc1c...

**Comment by ebfull** [comment]
@bmerge retry

**Comment by ebfull** [comment]
@bmerge force

**Comment by bmerge** [comment]
:bomb: Buildbot returned an error: `Authorization failed`

**Pull request closed without merging**
