### PR TITLE
Remove travis CI.

### PR DESCRIPTION
**Pull request by ebfull**

### CODE REVIEW

**Comment by ebfull** [comment]
@bmerge r+

**Comment by bmerge** [comment]
:pushpin: Commit c9677d8 has been approved by `ebfull`

**Comment by bmerge** [comment]
:hourglass: Testing commit c9677d8bd2ecfb7a069f55ba06b4ba029d203547 with merge 002c22bbde8310703a8799c42c07cdbd9dd4d7a6...

**Comment by bmerge** [comment]
:broken_heart: Test failed - [linux64-auto](http://ci.bellman.rs:8010//builders/linux64-auto/builds/0)

**Comment by ebfull** [comment]
@bmerge retry

**Comment by bmerge** [comment]
:hourglass: Testing commit c9677d8bd2ecfb7a069f55ba06b4ba029d203547 with merge ad48750dbb21639d2f98275cba99945ff6e1760c...

**Comment by bmerge** [comment]
:broken_heart: Test failed - [linux64-auto](http://ci.bellman.rs:8010//builders/linux64-auto/builds/1)

**Comment by bmerge** [comment]
:bomb: Failed to start rebuilding: `404 - No Such Resource`

**Comment by bmerge** [comment]
:hourglass: Testing commit c9677d8bd2ecfb7a069f55ba06b4ba029d203547 with merge 8ff6ce741a601e649e342754f3c19f51da28c067...

**Comment by bmerge** [comment]
:broken_heart: Test failed - [linux64-auto](http://ci.bellman.rs:8010/builders/linux64-auto/builds/2)

**Comment by ebfull** [comment]
@bmerge retry

**Comment by bmerge** [comment]
:zap: Previous build results for [windows64msvc-auto](http://ci.bellman.rs:8010/builders/windows64msvc-auto/builds/7) are reusable. Rebuilding only [linux64-auto](http://ci.bellman.rs:8010/builders/linux64-auto/builds/2)...

**Comment by bmerge** [comment]
:sunny: Test successful - [linux64-auto](http://ci.bellman.rs:8010/builders/linux64-auto/builds/3), [windows64msvc-auto](http://ci.bellman.rs:8010/builders/windows64msvc-auto/builds/7)
Approved by: ebfull
Pushing 8ff6ce741a601e649e342754f3c19f51da28c067 to master...

**Pull request merged**
